//
//  ExampleUsage.swift
//  CoreDataKit
//
//  Created by LammaTech on 2025.
//
//  This file demonstrates how to use CoreDataKit in your app.
//  Copy and adapt these examples for your own use case.
//

import Combine
import CoreData
import CoreDataKit
import Foundation
import SwiftInjected
import SwiftUI

// swiftlint:disable orphaned_doc_comment

// MARK: - Example 1: Define Your Managed Object

/// First, create your CoreData model (.xcdatamodeld) in Xcode with entities.
/// Then create a managed object subclass.
///
/// In your .xcdatamodeld:
/// - Entity: User
/// - Attributes: id (UUID), name (String), email (String), createdAt (Date)
///
/// The class name should end with "MO" suffix for auto entity name derivation.

// This would be auto-generated by Xcode or manually created:
// @objc(UserMO)
// public class UserMO: NSManagedObject {
//     @NSManaged public var id: UUID?
//     @NSManaged public var name: String?
//     @NSManaged public var email: String?
//     @NSManaged public var createdAt: Date?
// }

// extension UserMO: ManagedEntity {}

// MARK: - Example 2: Define Your Domain Model

/// Create a domain model that conforms to CoreDataMappable.
///
/// ```swift
/// struct User: CoreDataMappable, IdentifiableCoreDataMappable {
///     typealias ManagedObjectType = UserMO
///
///     let id: String
///     let name: String
///     let email: String
///     let createdAt: Date
///
///     @discardableResult
///     func store(in context: NSManagedObjectContext) -> UserMO? {
///         let request = UserMO.newFetchRequest()
///         request.predicate = .byId(id: id)
///         let userMO: UserMO
///
///         if let existing = try? context.fetch(request).first {
///             userMO = existing
///         } else {
///             guard let new = UserMO.insertNew(in: context) else { return nil }
///             userMO = new
///             userMO.id = UUID(uuidString: id)
///         }
///
///         userMO.name = name
///         userMO.email = email
///         userMO.createdAt = createdAt
///         return userMO
///     }
///
///     init?(managedObject: UserMO) {
///         guard let id = managedObject.id,
///               let name = managedObject.name,
///               let email = managedObject.email else { return nil }
///
///         self.id = id.uuidString
///         self.name = name
///         self.email = email
///         self.createdAt = managedObject.createdAt ?? Date()
///     }
///
///     init(id: String = UUID().uuidString, name: String, email: String, createdAt: Date = Date()) {
///         self.id = id
///         self.name = name
///         self.email = email
///         self.createdAt = createdAt
///     }
/// }
/// ```

// MARK: - Example 3: Create a Repository

/// Create a repository for your domain model.
///
/// ```swift
/// protocol UserRepositoryProtocol {
///     func getAll() -> AnyPublisher<[User], Error>
///     func getById(_ id: String) -> AnyPublisher<User?, Error>
///     func findByEmail(_ email: String) -> AnyPublisher<User?, Error>
///     func store(_ user: User) -> AnyPublisher<User, Error>
///     func delete(_ user: User) -> AnyPublisher<Void, Error>
/// }
///
/// final class UserRepository: BaseRepository<User>, UserRepositoryProtocol {
///
///     override func defaultFetchRequest() -> NSFetchRequest<UserMO> {
///         let request = UserMO.newFetchRequest()
///         request.sortDescriptors = [.descending("createdAt")]
///         request.fetchBatchSize = 20
///         return request
///     }
///
///     func findByEmail(_ email: String) -> AnyPublisher<User?, Error> {
///         let request = UserMO.newFetchRequest()
///         request.predicate = NSPredicate(format: "email == %@", email)
///         request.fetchLimit = 1
///         return persistentStore
///             .fetch(request) { User(managedObject: $0) }
///             .map(\.first)
///             .eraseToAnyPublisher()
///     }
/// }
/// ```

// MARK: - Example 4: Create Database Service

/// Create a database service that manages all repositories.
///
/// ```swift
/// final class DatabaseService {
///     let userRepository: UserRepository
///     let productRepository: ProductRepository
///
///     init(configuration: CoreDataConfiguration) {
///         let persistentStore = CoreDataStack(configuration: configuration)
///         userRepository = UserRepository(persistentStore: persistentStore)
///         productRepository = ProductRepository(persistentStore: persistentStore)
///     }
///
///     static func createDefault() -> DatabaseService {
///         // Load managed object model from bundle
///         guard let modelURL = Bundle.main.url(forResource: "MyDataModel", withExtension: "momd"),
///               let model = NSManagedObjectModel(contentsOf: modelURL) else {
///             fatalError("Failed to load CoreData model")
///         }
///
///         let config = CoreDataConfiguration(
///             modelName: "MyDataModel",
///             databaseFileName: "myapp.sqlite",
///             managedObjectModel: model
///         )
///         return DatabaseService(configuration: config)
///     }
/// }
/// ```

// MARK: - Example 5: SwiftInjected Integration

/// Setup dependencies at app launch.
///
/// ```swift
/// import SwiftInjected
///
/// @main
/// struct MyApp: App {
///     init() {
///         setupDependencies()
///     }
///
///     var body: some Scene {
///         WindowGroup {
///             ContentView()
///         }
///     }
/// }
///
/// func setupDependencies() {
///     let dependencies = Dependencies {
///         Dependency { DatabaseService.createDefault() }
///     }
///     dependencies.build()
/// }
/// ```

// MARK: - Example 6: Use in ViewModel

/// Inject the database service into your ViewModel.
///
/// ```swift
/// final class UserListViewModel: ObservableObject {
///     @Injected var database: DatabaseService
///
///     @Published var users: [User] = []
///     @Published var isLoading = false
///     @Published var error: Error?
///
///     private let cancelBag = CancelBag()
///
///     func loadUsers() {
///         isLoading = true
///         database.userRepository.getAll()
///             .receive(on: DispatchQueue.main)
///             .sink { [weak self] completion in
///                 self?.isLoading = false
///                 if case .failure(let error) = completion {
///                     self?.error = error
///                 }
///             } receiveValue: { [weak self] users in
///                 self?.users = users
///             }
///             .store(in: cancelBag)
///     }
///
///     func addUser(name: String, email: String) {
///         let user = User(name: name, email: email)
///         database.userRepository.store(user)
///             .receive(on: DispatchQueue.main)
///             .sink { [weak self] completion in
///                 if case .failure(let error) = completion {
///                     self?.error = error
///                 }
///             } receiveValue: { [weak self] savedUser in
///                 self?.users.insert(savedUser, at: 0)
///             }
///             .store(in: cancelBag)
///     }
///
///     func deleteUser(_ user: User) {
///         database.userRepository.delete(user)
///             .receive(on: DispatchQueue.main)
///             .sink { [weak self] completion in
///                 if case .failure(let error) = completion {
///                     self?.error = error
///                 }
///             } receiveValue: { [weak self] _ in
///                 self?.users.removeAll { $0.id == user.id }
///             }
///             .store(in: cancelBag)
///     }
/// }
/// ```

// MARK: - Example 7: Use in SwiftUI View

/// Access the ViewModel in your View.
///
/// ```swift
/// struct UserListView: View {
///     @StateObject private var viewModel = UserListViewModel()
///
///     var body: some View {
///         NavigationView {
///             List(viewModel.users, id: \.id) { user in
///                 VStack(alignment: .leading) {
///                     Text(user.name)
///                         .font(.headline)
///                     Text(user.email)
///                         .font(.subheadline)
///                         .foregroundColor(.secondary)
///                 }
///             }
///             .navigationTitle("Users")
///             .onAppear {
///                 viewModel.loadUsers()
///             }
///             .overlay {
///                 if viewModel.isLoading {
///                     ProgressView()
///                 }
///             }
///         }
///     }
/// }
/// ```

// MARK: - Example 8: Testing with Mock

/// Create a mock persistent store for testing.
///
/// ```swift
/// final class MockPersistentStore: PersistentStore {
///     var mockData: [Any] = []
///     var shouldFail = false
///     var mockError = NSError(domain: "Test", code: -1)
///
///     func count(_ fetchRequest: NSFetchRequest<some Any>) -> AnyPublisher<Int, Error> {
///         if shouldFail {
///             return Fail(error: mockError).eraseToAnyPublisher()
///         }
///         return Just(mockData.count)
///             .setFailureType(to: Error.self)
///             .eraseToAnyPublisher()
///     }
///
///     func fetch<T, V>(
///         _ fetchRequest: NSFetchRequest<T>,
///         map: @escaping (T) throws -> V?
///     ) -> AnyPublisher<[V], Error> {
///         if shouldFail {
///             return Fail(error: mockError).eraseToAnyPublisher()
///         }
///         let results = mockData.compactMap { $0 as? V }
///         return Just(results)
///             .setFailureType(to: Error.self)
///             .eraseToAnyPublisher()
///     }
///
///     func update<Result>(_ operation: @escaping DBOperation<Result>) -> AnyPublisher<Result, Error> {
///         if shouldFail {
///             return Fail(error: mockError).eraseToAnyPublisher()
///         }
///         // For testing, create an in-memory context
///         let container = NSPersistentContainer(name: "Test")
///         container.persistentStoreDescriptions.first?.type = NSInMemoryStoreType
///         // ... setup and execute
///         fatalError("Implement as needed for your tests")
///     }
/// }
/// ```

// swiftlint:enable orphaned_doc_comment
